---
# File: main.yml
# Type: task
# Part: Kaspersky

## Checks
- name: Kaspersky | Check architecture
  fail: msg="Kaspersky only support x86_64 architecture"
  when: ansible_architecture != 'x86_64'

## Install
- name: Kaspersky | Install
  include: install.yml
  when: not kaspersky_skip_install

## Stats
- name: Kaspersky | Stats
  include: stats.yml
  when: kaspersky_fetch_stats

## Check service
- name: Kaspersky | Check service daemon
  service: name=kes4lwks-supervisor state=started
