---
# File: main.yml
# Type: task
# Part: Mpv

- name: Mpv | Install ppa key
  apt_key: keyserver=keyserver.ubuntu.com id=8E51A6D660CD88D67D65221D90BD7EACED8E640A

- name: Mpv | Install ppa
  apt_repository: repo=ppa:mc3man/mpv-tests state=present

- name: Mpv | Install packages
  apt: name=mpv state={{ mpv_apt_state }} force=true
