---
# File: main.yml
# Type: defaults
# Part: beats

# Aptitude state
metricbeat_apt_state: "latest"

metricbeat_module_system_enabled: true
metricbeat_module_system_metricsets: [".*"]
metricbeat_module_system_period: "10s"
metricbeat_module_system_processes: [".*"]
metricbeat_module_system_cpu_ticks: false

metricbeat_module_redis_enabled: false
metricbeat_module_redis_hosts: ["localhost"]
metricbeat_module_redis_metricsets: [".*"]
metricbeat_module_redis_period: "10s"

metricbeat_module_mongodb_enabled: false
metricbeat_module_mongodb_hosts: ["localhost"]
metricbeat_module_mongodb_metricsets: [".*"]
metricbeat_module_mongodb_period: "10s"

metricbeat_service_enabled: true
metricbeat_service_state: "started"

metricbeat_output_protocol: "http"
metricbeat_output_path: ""
metricbeat_output_hosts:
  - "localhost:9000"
metricbeat_output_username: ""
metricbeat_output_password: ""
