---
# File: playbook.yml
# Type: playbook
# @cli vagrant destroy; vagrant up; rm -rf fetched/*
# @cli ansible-playbook -i vagrant_inventory playbook.yml

- name: Ansible setup
  hosts: all
  sudo: yes
  roles:
    - role: ansible/setup
      tags: ansible

- name: Fetch facts
  hosts: all
  sudo: yes
  roles:
    - role: ansible/facts
      tags: facts

- name: Setup ansible accelerated mode
  hosts: all
  sudo: yes
  roles:
    - role: ansible/accelerated
      tags: accelerated
    # - role: ansible/fireball
    #   tags: fireball


- name: Execute playbook
  # connection: fireball
  # accelerate: true
  hosts: all
  sudo: yes
  roles:
    - role: system/docker
      tags: docker
    - role: database/beanstalkd
      tags: beanstalkd
    - role: database/mysql
      tags: mysql
    - role: database/mongodb
      tags: mongodb
    - role: database/redis
      tags: redis
    - role: web/apache2
      tags: apache2
    - role: web/nginx
      tags: nginx
    - role: web/nodejs
      tags: nodejs
    - role: web/php5
      tags: php5
    - role: networking/transmission
      tags: transmission
