---
# File: playbook.yml
# Type: playbook
# @cli vagrant destroy; vagrant up; rm -rf fetched/*
# @cli ansible-playbook -i vagrant_inventory playbook.yml

- name: Ansible setup
  hosts: all
  sudo: yes
  tasks:
    - name: Install required packages
      apt: name={{ item }} update_cache=yes
      tags: apt_update
      with_items:
        - python-dev
        - python-software-properties
        - python-pip


- name: Fetch facts
  hosts: all
  sudo: yes
  roles:
    - role: ansible/facts
      tags: facts


- name: Setup ansible accelerated mode
  hosts: all
  sudo: yes
  roles:
    - role: ansible/accelerated
      tags: accelerated
    # - role: ansible/fireball
    #   tags: fireball


- name: Execute playbook
  # connection: fireball
  accelerate: true
  hosts: all
  sudo: yes
  roles:
    - role: databases/beanstalkd
      tags: beanstalkd
    - role: databases/mysql
      tags: mysql
    - role: databases/mongodb
      tags: mongodb
    - role: databases/redis
      tags: redis
    - role: webservers/apache2
      tags: apache2
    - role: webservers/nginx
      tags: nginx
    - role: webservers/nodejs
      tags: nodejs
    - role: webservers/php5
      tags: php5
