---
# File: main.yml
# Type: handler
# Part: MySQL

- name: start mysql
  service: name=mysql state=started
  when: not docker
- name: start mysql
  supervisorctl: name=program:mysqld state=started config=/etc/supervisor/supervisord.conf
  when: docker

- name: restart mysql
  service: name=mysql state=restarted
  when: not docker
- name: restart mysql
  supervisorctl: name=program:mysqld state=restarted config=/etc/supervisor/supervisord.conf
  when: docker
