---
# File: main.yml
# Type: defaults
# Part: MongoDB

# Aptitude state
mongodb_apt_state: "latest"

# Network configuration
mongodb_bind_address: "0.0.0.0"
mongodb_port: 27017

# User and group
mongodb_user: "mongodb"
mongodb_group: "mongodb"

# Default base directory (without trailing '/')
mongodb_path: "/var/lib/mongodb"
