---
# File: main.yml
# Type: task
# Part: cntlm

## Install
- name: cntlm | Install package
  apt: name=cntlm state={{ cntlm_apt_state }}

## Configuration
- name: cntlm | Deploy configuration
  template: src=cntlm.conf.j2 dest=/etc/cntlm.conf owner=root group=root mode=0600
  notify: restart cntlm
