---
# File: docker-gen.yml
# Type: task
# Part: Docker

- name: DockerGen | Fetch package
  action: get_url url=https://github.com/jwilder/docker-gen/releases/download/{{ docker_gen_version }}/docker-gen-linux-amd64-{{ docker_gen_version }}.tar.gz dest=/opt/docker-gen-linux-amd64-{{ docker_gen_version }}.tar.gz
    sha256sum={{ docker_gen_sha256sum }}
  register: result
- name: DockerGen | Extract package
  shell: rm /opt/local/bin/docker-gen; mkdir -p /opt/local/bin; tar -xvzf /opt/docker-gen-linux-amd64-{{ docker_gen_version }}.tar.gz -C /opt/local/bin; chmod +rx /opt/local/bin/docker-gen; ln -fs /opt/local/bin/docker-gen /usr/bin/docker-gen
  when: result | changed

