---
# File: docker-gen.yml
# Type: task
# Part: Docker

- name: DockerGen | Check directory
  file: state=directory path=/opt/downloads owner=root group=root mode=0775

- name: DockerGen | Fetch package
  get_url: url=https://github.com/jwilder/docker-gen/releases/download/{{ docker_gen_version }}/docker-gen-linux-amd64-{{ docker_gen_version }}.tar.gz
    dest=/opt/downloads/docker-gen-linux-amd64-{{ docker_gen_version }}.tar.gz
    checksum={{ docker_gen_checksum }}
  register: result
- name: DockerGen | Extract package
  shell: rm /opt/local/bin/docker-gen; mkdir -p /opt/local/bin; tar -xvzf /opt/downloads/docker-gen-linux-amd64-{{ docker_gen_version }}.tar.gz -C /opt/local/bin; chmod +rx /opt/local/bin/docker-gen
  when: result|changed
- name: DockerGen | Check link
  file: state=link path=/usr/bin/docker-gen src=/opt/local/bin/docker-gen

- name: DockerGen | Setup templates directory
  file: path=/etc/docker/templates state=directory

- name: DockerGen | Deploy hosts template
  shell: cp /etc/hosts /etc/docker/templates/hosts.orig
    creates=/etc/docker/templates/hosts.orig

- name: DockerGen | Deploy hosts template
  template: src=hosts.j2 dest=/etc/docker/templates/hosts.tmpl owner=root group=root mode=0644 backup=no
  notify: restart docker-gen

- name: DockerGen | Deploy service configuration
  template: src=init_docker-gen.conf.j2 dest=/etc/init/docker-gen.conf owner=root group=root mode=0644 backup=no
  notify: restart docker-gen
