---
# File: main.yml
# Type: task
# Part: Watchdog

- name: Watchdog | Check Intel processor
  set_fact: watchdog_module="iTCO-wdt"
  when: "'Intel' in ansible_processor[0]"
- name: Watchdog | Check ARM processor
  set_fact: watchdog_module="bcm2835_wdt"
  when: "'ARMv7' in ansible_processor[0]"

- name: Watchdog | Install package
  apt: name=watchdog

- name: Watchdog | Deploy configuration
  template:
    src: watchdog.conf.j2
    dest: /etc/watchdog.conf
    owner: root
    group: root
    mode: '0600'
  notify: start watchdog

- name: Watchdog | Deploy service configuration
  template:
    src: systemd_system_watchdog.service.j2
    dest: /lib/systemd/system/watchdog.service
    owner: root
    group: root
    mode: '0600'
  notify: start watchdog
  when: ansible_distribution_major_version|int == 16

- name: Watchdog | Deploy defaults
  template:
    src: default_watchdog.j2
    dest: /etc/default/watchdog
    owner: root
    group: root
    mode: '0644'

- include: configure-tco.yml
  when: watchdog_module == 'iTCO-wdt'

- name: Watchdog | Enable service
  service: name=watchdog state={{ watchdog_service_state }} enabled={{ watchdog_service_enabled }}
  when: ansible_distribution_major_version|int < 16

- name: Watchdog | Enable service
  shell: systemctl enable watchdog; service watchdog start
  when: ansible_distribution_major_version|int == 16
