---
# File: main.yml
# Type: handler
# Part: SSH

- name: start ssh
  service: name=ssh state=started

- name: restart ssh
  service: name=ssh state=restarted

- name: start ufw
  service: name=ufw state=started

- name: restart ufw
  service: name=ufw state=restarted
