---
# File: main.yml
# Type: defaults
# Part: Docker

# Aptitude state
docker_apt_state: "latest"

# User and group
docker_user: "www-data"
docker_group: "www-data"

# Legacy Options
docker_opts: ""
# Options
docker_bip: ""
docker_log_driver: ""
docker_storage_driver: "aufs"

# DockerCompose
docker_compose_install: true
docker_compose_version: "1.21.2"
docker_compose_checksum: "sha1:3a6a0a2b1ec85fb74159891c4bae672b342d039a"

# DockerGen
docker_gen_install: false
docker_gen_version: "0.7.3"
docker_gen_checksum: "sha1:9bd460f66e2e26323ea439c11956a145bb305c53"
