---
# File: main.yml
# Type: defaults
# Part: Docker

# Aptitude state
docker_apt_state: "latest"

# User and group
docker_user: "www-data"
docker_group: "www-data"

# DockerCompose
docker_compose_install: true
docker_compose_version: 1.6.2
docker_compose_checksum: "sha1:82129d4e90c7544a52738a570747d653bdb656db"

# DockerGen
docker_gen_install: false
docker_gen_version: "0.7.1"
docker_gen_checksum: "sha1:73521458bb316f19ebc3d26d083aa79a19271777"
