---

# - name: Mediainfo | Install ppa key
#   apt_key: keyserver=keyserver.ubuntu.com id=B34F70C93804BEA383522B2061260473F9D8BC54
- name: Mediainfo | Install ppa
  apt_repository: repo="{{ item }}" validate_certs={{ nodejs_validate_certs }}
  with_items:
    - "deb https://mediaarea.net/repo/deb/ubuntu {{ ansible_distribution_release }} main"
- name: Mediainfo | Install package
  apt: name=mediainfo state=latest

