---
# File: main.yml
# Type: task
# Part: Beanstalkd


## Install
- name: Beanstalkd | Install package
  apt: name=beanstalkd state={{ beanstalkd_apt_state }}
  notify: restart beanstalkd

## Setup custom location
- include: location.yml
  when: "'{{ beanstalkd_path }}' != '/var/lib/beanstalkd'"

## Configure service
- include: configure-init.yml
  when: not docker
- include: configure-supervisor.yml
  when: docker
