---
# File: main.yml
# Type: task
# Part: Ansible/Setup


## Install
- name: Setup | Update aptitude
  apt: update_cache=yes cache_valid_time=3600
- name: Setup | Install ansible required packages
  apt: name={{ item }} state=latest
  with_items:
    - python-apt
    - python-dev
    - python-pip
    - python-pycurl
    - python-software-properties
