---
# File: main.yml
# Type: task
# Part: Redis

## Install
- include: install-arm.yml
  when: ansible_architecture == 'armv6l' or ansible_architecture == 'armv7l'
# - include: install-ubuntu.yml
#   when: ansible_distribution == 'Ubuntu'

# ## Setup custom location
# - include: location.yml
#   when: "'{{ redis_path }}' != '/var/lib/redis'"

# ## Configure
# - name: Redis | Backup configuration
#   shell: creates=/etc/redis/redis.conf.orig cp /etc/redis/redis.conf /etc/redis/redis.conf.orig
#   register: result
# - fetch: src=/etc/redis/redis.conf.orig dest=fetched
#   when: result|changed
# - name: Redis | Deploy configuration
#   template: src=redis_redis.conf.j2 dest=/etc/redis/redis.conf owner=root mode=0644 backup=yes
#   notify: restart redis
#   register: result
# - fetch: src=/etc/redis/redis.conf dest=fetched
#   when: result.changed

# ## Make sure service is running
# - name: Redis | Check daemon
#   service: name=redis-server state=started
