---
# File: main.yml
# Type: handler
# Part: MongoDB

- name: start mongod
  service: name=mongod state=started
- name: reload mongod
  service: name=mongod state=reloaded
- name: restart mongod
  service: name=mongod state=restarted
