---
# File: main.yml
# Type: task
# Part: OpenVPN | Default (Ubuntu)

## Install
- name: OpenVPN | Install package
  apt: name={{ item }} state={{ openvpn_apt_state }}
  with_items:
    - openvpn
  notify: restart openvpn
