---
# File: main.yml
# Type: task
# Part: OpenVPN

## Install
- include: install-arm.yml
  when: ansible_architecture == 'armv6l' or ansible_architecture == 'armv7l'
- include: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Configure client / server
- name: OpenVPN | Load configuration defaults
  include_vars: "vars/openvpn/{{ openvpn_config }}/main.yml"
  when: openvpn_config is defined
- name: OpenVPN | Configure client
  include: configure-client.yml
  when: openvpn_config is defined and openvpn_type == 'client'

## Configure service
- name: OpenVPN | Backup service configuration
  shell: creates=/etc/init.d/openvpn.orig.disabled cp /etc/init.d/openvpn /etc/init.d/openvpn.orig.disabled
  ignore_errors: True
  register: result
- fetch: src=/etc/init.d/openvpn.orig.disabled dest=fetched/{{ ansible_host }}/etc/init.d/openvpn.orig flat=yes
  when: result | changed
- name: OpenVPN | Deploy service configuration
  template: src=init.d_openvpn.j2 dest=/etc/init.d/openvpn owner=root group=root mode=0755 backup=no
  notify: restart openvpn
  register: result
- fetch: src=/etc/init.d/openvpn dest=fetched
  when: result | changed

## Make sure service is running
- name: OpenVPN | Check daemon
  service: name=openvpn state=started enabled=yes
