---
# File: configure-upstart.yml
# Type: task
# Part: MongoDB

- name: MongoDB | Backup service configuration
  command: cp /etc/init/{{ mongodb_service }}.conf /var/backups/{{ mongodb_service }}.conf.bak owner=root group=root mode=0644
  args:
    creates: /var/backups/{{ mongodb_service }}.conf.bak
  register: result
- fetch: src=/var/backups/{{ mongodb_service }}.conf dest=fetched
  when: result|changed
- name: MongoDB | Deploy upstart service configuration
  template: src=init_mongod.conf.j2 dest=/etc/init/{{ mongodb_service }}.conf owner=root group=root mode=0755 backup=no
  notify: restart mongod
  register: result
- fetch: src=/etc/init/{{ mongodb_service }}.conf dest=fetched
  when: result|changed
