---
# File: main.yml
# Type: task
# Part: Mongo

- name: MongoDB | Check system
  fail: msg="Only Ubuntu is supported"
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_major_version|int < 14

## Install
- include: install.yml
  when: ansible_architecture == "x86_64"
- include: install-arm.yml
  when: "'arm' in ansible_architecture"

## Configure
- include: configure.yml
  when: ansible_architecture == "x86_64"

## Configure service
- include: configure-systemd.yml
  when: ansible_architecture == "x86_64" and not docker and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16
# - include: configure-upstart.yml
#   when: not docker and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14
# - include: configure-supervisor.yml
#   when: docker

## Check service
- name: MongoDB | Check service daemon
  service: name={{ mongodb_service }} state=started enabled=yes
