---
# File: main.yml
# Type: defaults
# Part: ufw

ssh_port: 22
ufw_policies:
  - { direction: 'incoming', policy: 'deny' }
  - { direction: 'outgoing', policy: 'allow' }
ufw_reset_rules: False
ufw_rules:
  - { rule: 'allow', proto: 'tcp', port: 22 }
